<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.6" />
	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adocao.Domain\Adocao.Domain.csproj" />
    <ProjectReference Include="..\Adocao.Infra\Adocao.Infra.csproj" />
  </ItemGroup>

</Project>
